### ISSUE TITLE
Eigen error: template declaration

### ISSUE THREAD

**Issue by kashimAstro** [memo/ofxMSATensorFlow#17] opened 2017-03-30 13:30 UTC
Hi @memo,

first of all, thank you so much for porting to the version 1.0 of TF!
I am carrying some of my projects with TF1.0 in openFrameworks using your addons.

trying to compile example-basic with .so CPU without OPT, i am having this problem with Eigen:

`error: template declaration of ‘const Eigen::internal::FixedInt<N> Eigen::fix’ static const internal::FixedInt<N> fix{};`

i think, this error is related to the completion flag "c++14" (but I'm not sure about that)

```
#if EIGEN_HAS_CXX14
template<int N>
static const internal::FixedInt<N> fix{};
#else
template<int N>
inline internal::FixedInt<N> fix() { return internal::FixedInt<N>(); }
.....

```
when in openframeworks compiling addons with flag "c++14"
preprocessor seems to enter in this: #if EIGEN_HAS_CXX14

for some reason unknown to me my compiler is not happy with this syntax.

But if I try compiling with flag "c++11" the only problem I have the references undefined, that's what I expected because the .so was compiled with the flag "c++14"

you have any advice on what you can investigate to solve this?

my environment:

```
OF 9.8
Debian Jessie
g++ (Debian 4.9.2-10) 4.9.2
```

Thanks for the attention

Ciao
Dario

**Comment by kashimAstro** [comment] 2017-03-30 14:39
I solved Eigen problem in a mode very inappropriate, there remain some problems: undefined reference
but I think I can fix this by recompiling the .so

thanks and good day :) 
Dario

**Comment by memo** [comment] 2017-06-12 19:06
Hi I have no idea what the problem is I'm afraid as I didn't get this. If you've managed to fix the problem I'll close the issue?

**Closed by memo** 2017-06-12 19:06 UTC

**Comment by kashimAstro** [comment] 2017-07-06 13:09
Sorry for long delay, Yes, closed, i have solved this problem...

**Comment by dledents** [comment] 2017-10-06 05:28
Hi. How did you solve it? I have the same problem with template declaration of the "fix{}" when I compile with c++ 14.

**Comment by andres115** [comment] 2017-10-24 20:11
also have this problem, is it okay for you to share the answer?

**Comment by dledents** [comment] 2017-10-25 04:36
Yes, It is ok,

**Comment by kashimAstro** [comment] 2017-10-25 09:33
@dledents sorry, but I missed this message.
I solved this problem by recompiling the .so of tensorflow.

**Comment by Dazzid** [comment] 2019-04-18 11:28
Hi,
I'm trying to compile in OSX but also have the same error you posted before. I compiled Tensorflow following its tutorial using "bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package" 
but I don't get where is .so file. 
Any suggestion?
